sudo: required
services: docker
language: generic

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.2

before_install:
    # upgrade docker-engine to specific version. Also installs docker-compose
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty

script:
    - ./build.sh
    - ./test.sh
    - curl -O https://raw.githubusercontent.com/cyber-dojo/ruby/master/push.sh
    - chmod +x push.sh
    - ./push.sh
