sudo: required

services:
  - docker

language: ruby

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.1
        - DOCKER_MACHINE_VERSION=0.8.1
        - DOCKER_COMPOSE_VERSION=1.8.0
        - HOME_DIR=${TRAVIS_BUILD_DIR}

before_install:
    # list docker-engine versions
    - apt-cache madison docker-engine

    # travis documentation says I'm in trusty container
    - lsb_release -a | grep trusty

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty
    - docker version | grep ${DOCKER_ENGINE_VERSION}

    # reinstall docker-compose at specific version
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - docker-compose version | grep ${DOCKER_COMPOSE_VERSION}

    # install docker-machine at specific version
    - curl -L https://github.com/docker/machine/releases/download/v{DOCKER_COMPOSE_VERSION}/docker-machine-`uname -s`-`uname -m` > docker-machine
    - chmod +x docker-machine
    - sudo mv docker-machine /usr/local/bin
    #- docker-machine version  # FAILS?

    # smoke test
    - docker run --rm hello-world
    - docker images

script:

    - cd ${HOME_DIR}/sinatra && ./build-image.sh
    - cd ${HOME_DIR}/client  && ./build-image.sh
    - cd ${HOME_DIR}/server  && ./build-image.sh
    - cd ${HOME_DIR} && docker-compose up -d
    - cd ${HOME_DIR} && ./test.sh
