
differ_client:
  image: differ_client
  container_name: differ_client
  links:
    - "differ"
  ports:
    - "4568:4568"


differ:
  image: cyberdojo/differ
  container_name: differ
  environment:
    - DIFFER_CLASS_LOG=StdoutLogger
    - DIFFER_CLASS_SHELL=HostSheller
    - DIFFER_CLASS_GIT=HostGitter
    - DIFFER_CLASS_FILE=FileWriter
  ports:
    - "4567:4567"

