
version: '2'

services:
  differ_client:
    image: cyberdojo/differ_client
    container_name: differ_client
    command: [ "foreman", "start", "-d", "${APP_DIR}" ]
    ports: [ "${CLIENT_PORT}:${CLIENT_PORT}" ]
    links: [ differ_server ]

  differ_server:
    image: cyberdojo/differ
    container_name: differ_server
    ports: [ "${SERVER_PORT}:${SERVER_PORT}" ]
    command: [ "foreman", "start", "-d", "${APP_DIR}" ]

