
version: '2'

services:
  differ_client:
    user: nobody
    image: cyberdojo/differ_client
    container_name: differ_client
    command: [ "foreman", "start", "-d", "/app" ]

  differ_server:
    user: nobody
    image: cyberdojo/differ
    container_name: differ_server
    command: [ "foreman", "start", "-d", "/app" ]

