
differ_client:
  image: differ_client
  container_name: differ_client
  links:
    - "differ_server"
  ports:
    - "4568:4568"


differ_server:
  image: differ_server
  container_name: differ_server
  environment:
    - DIFFER_CLASS_LOG=StdoutLogger
    - DIFFER_CLASS_SHELL=HostSheller
    - DIFFER_CLASS_GIT=HostGitter
    - DIFFER_CLASS_FILE=FileWriter
  ports:
    - "4567:4567"

