
version: '2'

services:
  differ_client:
    user: nobody
    image: cyberdojo/differ_client
    container_name: differ_client
    ports: [ "4568:4568" ]

  differ_server:
    user: nobody
    image: cyberdojo/differ
    container_name: differ_server
