
version: '2'

services:
  differ_client:
    user: nobody
    image: cyberdojo/differ_client
    container_name: differ_client
    build:
      context: client
      args:
        PORT: 4568
    ports: [ "4568:4568" ]

  differ:
    user: nobody
    image: cyberdojo/differ
    container_name: differ_server
    read_only: true
    tmpfs: /tmp
    build:
      context: server
      args:
        PORT: 4567
