
version: '2.2'

services:

  differ-client:
    build:
      context: test_client
    image: cyberdojo/differ-client
    init: true
    container_name: test-differ-client
    user: nobody
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    ports:
      - 4568:4568


  differ-server:
    build:
      context: .
      args:
        - SHA
    image: cyberdojo/differ
    container_name: test-differ-server
    environment:
      - NO_PROMETHEUS
    volumes:
      - ./test_server:/app/test:ro
    ports:
      - 4567:4567
    init: true
    user: nobody
    read_only: true
    tmpfs:
      - /tmp:exec,mode=1777 # Sticky bit must be set on /tmp otherwise
                            # Dir.mktmpdir(id,'/tmp') complains
    restart: 'no'
