
version: '2.2'

services:

  differ_client:
    build:
      context: client
      args:
        CYBER_DOJO_HOME: ${CYBER_DOJO_HOME}
        PORT: ${CYBER_DOJO_DIFFER_CLIENT_PORT}
    image: cyberdojo/differ-client
    init: true
    container_name: test-differ-client
    user: nobody
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - ./client/test:${CYBER_DOJO_HOME}/test:ro
    environment:
      - CYBER_DOJO_DIFFER_SERVICE_NAME
      - CYBER_DOJO_DIFFER_SERVICE_PORT
      - CYBER_DOJO_COVERAGE_ROOT
    ports: [ "${CYBER_DOJO_DIFFER_CLIENT_PORT}:${CYBER_DOJO_DIFFER_CLIENT_PORT}" ]

  differ:
    build:
      context: server
      args:
        CYBER_DOJO_HOME: ${CYBER_DOJO_HOME}
        PORT: ${CYBER_DOJO_DIFFER_SERVICE_PORT}
    image: cyberdojo/differ
    container_name: test-differ-server
    init: true
    user: nobody
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - ./server/test:${CYBER_DOJO_HOME}/test:ro
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
