
differ_client:
  image: differ_client
  container_name: differ_client
  links:
    - "differ"
  ports:
    - "4568:4568"


differ:
  user: nobody
  image: cyberdojo/differ
  container_name: differ
  ports:
    - "4567:4567"

