
differ_client:
  image: differ_client
  container_name: differ_client
  entrypoint:
    - foreman
    - start
    - -d
    - ${APP_DIR}
  links:
    - differ
  ports:
    - 4568:4568


differ:
  user: nobody
  image: cyberdojo/differ
  container_name: differ
  entrypoint:
    - foreman
    - start
    - -d
    - ${APP_DIR}
  ports:
    - 4567:4567

