
version: '3.7'

services:

  differ-client:
    build:
      args: [ CYBER_DOJO_DIFFER_DEMO_PORT ]
      context: test_client
    container_name: test-differ-client
    image: cyberdojo/differ-client
    init: true
    ports: [ "${CYBER_DOJO_DIFFER_CLIENT_PORT}:${CYBER_DOJO_DIFFER_CLIENT_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    user: nobody

  differ-server:
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_DIFFER_PORT ]
      context: app
    container_name: test-differ-server
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_DIFFER_IMAGE}
    init: true
    ports: [ "${CYBER_DOJO_DIFFER_PORT}:${CYBER_DOJO_DIFFER_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: [ "/tmp:exec,mode=1777" ] # [1]
    user: nobody
    volumes: [ "./test_server:/app/test:ro" ]

# [1] Sticky bit must be set on /tmp otherwise
#     Dir.mktmpdir(id,'/tmp') complains
