
version: '2.2'

services:

  differ_client:
    build:
      context: client
    image: cyberdojo/differ-client
    init: true
    container_name: test-differ-client
    user: nobody
    read_only: true
    tmpfs: /tmp
    restart: 'no'


  differ:
    build:
      context: .
    image: cyberdojo/differ
    container_name: test-differ-server
    init: true
    user: nobody
    read_only: true
    tmpfs: /tmp
    restart: 'no'
