
fullnameOverride: "differ"

replicaCount: 3

volumes:
  - name: differ-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "64Mi"

service:
  port: 4567
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4567"

containers:
  - name: differ
    image: cyberdojo/differ
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: differ-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      limits:
        memory: 32Mi
      requests:
        memory: 32Mi
    livenessProbe:
      path: /alive?
      port: 4567
    readinessProbe:
      path: /ready?
      port: 4567

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
